version: '2.1'
services:
  sftpserver:
    container_name: sftpserver
    image: atmoz/sftp:alpine
    volumes:
      - ./share:/home/user/share
      - ./server/ssh_host_rsa_key:/etc/ssh/ssh_host_ed25519_key
      - ./server/ssh_client_rsa_key.pub:/home/user/.ssh/keys/ssh_client_rsa_key.pub:ro
    working_dir: /home/user
    ports:
      - "2222:22"
    command: user:password:::share
